# Generated by Django 4.2.7 on 2023-11-12 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default='No asignado', max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, default='No asignado', max_length=9, null=True)),
                ('curso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Curso.curso')),
            ],
        ),
    ]
