# Generated by Django 4.2.7 on 2023-11-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.CharField(blank=True, default='No asignado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, default='No asignado', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, default='No asignado', max_length=254, null=True),
        ),
    ]
