# Generated by Django 4.2.7 on 2023-11-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='curso',
            new_name='cursoid',
        ),
    ]
