# Generated by Django 4.2.7 on 2023-11-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_remove_alumno_fecha_nacimiento_alumno_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='DNI',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
